tunnel: prism-aiads
credentials-file: /home/tokyo/.cloudflared/d69b9706-62c7-4d67-9aef-ba17bd3e0455.json

ingress:
  - hostname: prismpublication.com
    service: http://localhost:8080
  - hostname: www.prismpublication.com
    service: http://localhost:8080
  - service: http_status:404
